language: node_js
node_js:
  - "8"

deploy:
  provider: script
  script: "cp .npmrc.template .npmrc && npm publish dist"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    condition: $TRAVIS_TAG = deploy