language: node_js
node_js:
  - "8"


install:
  - cd ./modules/json-playback-recorder-ts
  - npm install
  - cd ../..

script:
  - cd ./modules/json-playback-recorder-ts
  - npm run test
  - npm run test
  - cp .npmrc.template .npmrc
  - npm deprecate json-playback-recorder-ts@0.1.0 "Combining a large number of Observables has proved totally impractical. Use version 0.2.0."
  - cd ../..
  - cd ./modules/json-pr-integration-test
  - npm install --no-package-lock
  - npm run test
  - cd ../..

deploy:
  provider: script
  script: "cd ./modules/json-playback-recorder-ts && cp .npmrc.template .npmrc && npm publish ../../dist/json-playback-recorder-ts && cd ../.."
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    condition: $TRAVIS_TAG =~ ^(deploy_.*|publish_.*)$