language: node_js
node_js:
  - "8"

deploy:
  - provider: script
    script: "foobaar && cp .npmrc.template .npmrc && npm publish dist"
    skip_cleanup: true
    on:
      tags: deploy
  - provider: script
    script: "echo none"
    skip_cleanup: true
    on:
      all_branches: true