language: node_js
node_js:
  - "8"


install:
  - cd ./modules/json-playback-recorder-ts
  - npm install
  - cd ../..

script:
  - cd ./modules/json-playback-recorder-ts
  - npm run test
  - cd ../..
  - cd ./modules/json-pr-integration-test
  - npm install
  - npm run test
  - cd ../..

deploy:
  provider: script
  script:
    - cp .npmrc.template .npmrc && npm publish ./dist/json-playback-recorder-ts
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    condition: $TRAVIS_TAG =~ ^(deploy_.*|publish_.*)$
