language: node_js
node_js:
  - "8"

deploy:
  - provider: script
    script: "cp .npmrc.template .npmrc && npm publish dist"
    on:
      tags: deploy
  - provider: script
    script: echo none
    